name = "swiss-qr-bill"
version = "0.1.0"
entrypoint = "swiss-qr-bill.typ"
authors = ["Philipp Drebes <@philippdrebes>"]
license = "LGPL-3.0-only"
description = "A Swiss QR bill generator for Typst."
repository = "https://github.com/philippdrebes/typst-swiss-qr-bill"
exclude = ["examples/"]
keywords = ["qr-bill", "payment", "swiss", "switzerland", "invoice", "finance"]
categories = ["components"]
disciplines = ["business"]
